name: Step 6, Add enemies

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_add-enemies-step-6-event:
    name: On add-enemies-step-6-event
    needs: get_current_step

    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 6 }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update to step 7
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 6
          to_step: 7
          branch_name: main
